spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
      routes:
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/reservations/**
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/api/rooms/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**